# loan prediction using different classifiaction model

In [206]:
import pandas as pd
import numpy as np

In [207]:
df = pd.read_csv('.\\Documents\\indexing\\data_python.csv')

In [208]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [209]:
df.shape

(614, 13)

In [210]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [211]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [212]:
df.fillna(method='bfill',inplace=True)

In [213]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [214]:
df.Loan_Status.unique()

array(['Y', 'N'], dtype=object)

# label Encoding

In [215]:
from sklearn import preprocessing

In [216]:
label_encoder = preprocessing.LabelEncoder()

In [217]:
df['Loan_Status']= label_encoder.fit_transform(df['Loan_Status'])   
df['Loan_Status'].unique() 

array([1, 0])

In [218]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area  Loan_Status  
0             1.0         Urban            1  
1             1.0         Rural            0  
2             1.0         Urban            1  
3             1.0         Urban            1  
4             1.0         Urban            1

In [220]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [221]:
df['Gender']= label_encoder.fit_transform(df['Gender'])   
df['Gender'].unique() 

array([1, 0])

In [222]:
df.Married.unique()

array(['No', 'Yes'], dtype=object)

In [223]:
df['Married']= label_encoder.fit_transform(df['Married'])   
df['Married'].unique() 

array([0, 1])

In [224]:
df.Education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [225]:
df['Education']= label_encoder.fit_transform(df['Education'])   
df['Education'].unique() 

array([0, 1])

In [226]:
df.Self_Employed.unique()

array(['No', 'Yes'], dtype=object)

In [227]:
df['Self_Employed']= label_encoder.fit_transform(df['Self_Employed'])   
df['Self_Employed'].unique() 

array([0, 1])

In [228]:
df.Property_Area.unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [229]:
df['Property_Area']= label_encoder.fit_transform(df['Property_Area'])   
df['Property_Area'].unique() 

array([2, 0, 1])

In [230]:
df.head()

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0  LP001002       1        0          0          0              0   
1  LP001003       1        1          1          0              0   
2  LP001005       1        1          0          0              1   
3  LP001006       1        1          0          1              0   
4  LP001008       1        0          0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [240]:
df[df.Dependents=='3+']

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
7    LP001014       1        1         3+          0              0   
34   LP001100       1        0         3+          0              0   
61   LP001206       1        1         3+          0              0   
68   LP001238       1        1         3+          1              1   
73   LP001250       1        1         3+          1              0   
74   LP001253       1        1         3+          0              1   
78   LP001263       1        1         3+          0              0   
79   LP001264       1        1         3+          1              1   
109  LP001384       1        1         3+          1              0   
126  LP001448       1        1         3+          0              0   
135  LP001488       1        1         3+          0              0   
155  LP001536       1        1         3+          0              0   
171  LP001585       1        1         3+          0              0   
172  LP001586       1        1         3+          1              0   
177  LP001610       1        1         3+          0              0   
202  LP001682       1        1         3+          1              0   
211  LP001711       1        1         3+          0              0   
213  LP001715       1        1         3+          1              1   
215  LP001720       1        1         3+          1              0   
255  LP001846       0        0         3+          0              0   
257  LP001854       1        1         3+          0              0   
259  LP001864       1        1         3+          1              0   
267  LP001882       1        1         3+          0              0   
295  LP001949       1        1         3+          0              0   
321  LP002053       1        1         3+          0              0   
324  LP002065       1        1         3+          0              0   
338  LP002113       0        0         3+          1              0   
340  LP002115       1        1         3+          1              0   
343  LP002126       1        1         3+          1              0   
352  LP002141       1        1         3+          0              0   
359  LP002160       1        1         3+          0              0   
376  LP002219       1        1         3+          0              0   
390  LP002255       1        0         3+          0              0   
391  LP002262       1        1         3+          0              0   
409  LP002317       1        1         3+          0              0   
442  LP002418       1        0         3+          1              0   
461  LP002484       1        1         3+          0              0   
466  LP002500       1        1         3+          1              0   
472  LP002519       1        1         3+          0              0   
481  LP002536       1        1         3+          1              0   
515  LP002659       1        1         3+          0              0   
522  LP002692       1        1         3+          0              1   
531  LP002720       1        1         3+          0              0   
539  LP002740       1        1         3+          0              0   
557  LP002795       1        1         3+          0              1   
567  LP002837       1        1         3+          0              0   
574  LP002863       1        1         3+          0              0   
592  LP002933       1        0         3+          0              1   
600  LP002949       0        0         3+          0              0   
602  LP002953       1        1         3+          0              0   
610  LP002979       1        1         3+          0              0   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
7               3036             2504.0       158.0             360.0   
34             12500             3000.0       320.0             360.0   
61              3029                0.0        99.0             360.0   
68              7100 

In [279]:
df.replace(to_replace='3+',value='4',inplace=True)

# Train_Test split

In [280]:
train = df.drop(['Loan_ID','Loan_Status'],axis=1)

In [281]:
target = df.Loan_Status

# 1st model Logistic_regression

In [282]:
from sklearn.linear_model import LogisticRegression

In [283]:
log_reg = LogisticRegression()

In [284]:
log_reg.fit(train,target)

C:\Users\Rahul Sain\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [285]:
pred = log_reg.predict(train)

In [286]:
from sklearn.metrics import accuracy_score

In [287]:
accuracy_score(pred,target)*100

80.29315960912052

# 2nd model Decision_Tree_Classifier

In [294]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)

In [295]:
clf.fit(train,target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [296]:
pred1 = clf.predict(train)
pred1

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [320]:
accuracy_score(pred1,target)*100

100.0

# 3rd model Random_Forest_classifier

In [298]:
from sklearn.ensemble import RandomForestClassifier

In [315]:
clf1 = RandomForestClassifier(max_depth=15, random_state=0)

In [316]:
clf1.fit(train,target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=15, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [317]:
pred2 = clf1.predict(train)

In [318]:
pred2

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [319]:
accuracy_score(pred2,target)*100

99.8371335504886